name: release
on:
  push:
    tags:        
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v1
    - name: Login to Docker Hub
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Build amd64 image
      run: |
        TAG=${GITHUB_REF}
        INDEX=${TAG%v*}
        VERSION=${TAG:${#INDEX}+1}
        docker build -f Dockerfile.amd64 -t manorrock/tomcat:amd64-$VERSION .
        docker push manorrock/tomcat:amd64-$VERSION
    - name: Push Docker manifest
      run: |
        TAG=${GITHUB_REF}
        INDEX=${TAG%v*}
        VERSION=${TAG:${#INDEX}+1}
        export DOCKER_CLI_EXPERIMENTAL=enabled
        docker manifest create manorrock/tomcat:$VERSION \
          manorrock/tomcat:amd64-$VERSION
        docker manifest annotate manorrock/tomcat:$VERSION \
          manorrock/tomcat:amd64-$VERSION --os linux --arch amd64
        docker manifest push manorrock/tomcat:$VERSION
